### ISSUE TITLE
Unable to delete by key

### ISSUE THREAD

**Issue by Jacox98** [AkashBabu/redis-json#10]
Hi everyone,

I have a problem with my project, I can't delete the saved value by key.

redis.del (key)

// or
jsonCache.del (key)

Please help me

**Comment by AkashBabu** [comment]
Hi @Jacox98 , we add a prefix to every key before saving the same in Redis, this helps us isolate the keys stored using redis-json library. So you can't delete the keys directly using `redis.del(key)`.
However I don't understand why `jsonCache.del(key)` isn't working for you. So can you please help me with the complete code, such that it will be easier for me to debug your problem ?

**Comment by Jacox98** [comment]
Thanks @AkashBabu for the fast response.

Simply json Cache.del is not a function

and when I use redis.del the keys are not deleted, both versions with and without prefix remain.

Thanks again for the help

![image](https://user-images.githubusercontent.com/35966887/90497609-8e076b80-e147-11ea-9ccb-e045d8b9e711.png)

For now I have solved this

redis.del('jc:' + req.params.uuid + '_t')
redis.del('jc:' + req.params.uuid)

**Comment by AkashBabu** [comment]
oh!! I'm really sorry, I didn't notice that `.del` method was not existing.
Btw I'll consider this as a feature request and will work on the same.

Thanks for bringing this up 🙂

**Comment by AkashBabu** [comment]
Hi @Jacox98 , please update your library to `redis-json@4.1.0` and you'll be able to find `.del` method 🎉
