### ISSUE TITLE
Is it possible to update nested object?

### ISSUE THREAD

**Issue by C0D1NGD0J0** [AkashBabu/redis-json#12]
Hi,

Please I would like to know if its possible to dynamically update a nested object? 

===e.g===
const user = {
  name: 'redis-json',
  age: 25,
  address: {},
  friends: []
}

await jsonCache.set('123', user);

const user = await jsonCache.get('123');
// output
// {
//   name: 'redis-json',
//   age: 25,
//   address: {},
//   friends: []
// }

user.friends.push({name: 'tom'}, {name: 'jerry});
await jsonCache.set('123', ????);  ===> what do I pass as the second argument? (user object of the updated property?

Also, can I dynamically add objects to the address property?
===e.g===
user.address[new-key] = new-value;
await jsonCache.set('123', ????);  ===> what do I pass as the second argument? (user object of the updated property?

**Comment by AkashBabu** [comment]
Hi @C0D1NGD0J0 , 
Yes it is possible to dynamically update nested objects.
Just FYI, this library uses RedisDB as a cache, so `user` object reference is not maintained in the DB, which means after you've modified the nested object, you can go ahead and save it the same way you did before.
```JS
const user = {
name: 'redis-json',
age: 25,
address: {},
friends: []
}
await jsonCache.set('123', user);

user.friends.push({name: 'tom'}, {name: 'jerry});
// 👇🏼 This works absolutely fine. 
// It will merge the update user object with the one
// already present in the cache
await jsonCache.set('123', user); 

user.address["new-key"] = "new-value";
await jsonCache.set('123', user); // <- This also works fine.
```
But please note that `.set()` will merge the new data (`user` object) with the one that is already existing in the cache. But if you wish to replace the entire object for the `key: 123`, then use `.rewrite()` method as `.rewrite('123', user)`.   
So:
```JS
const obj1 = {name: 'test1'}
await jsonCache.set('obj1', obj1);

const obj2 = {age: 21}
await jsonCache.set('obj1', obj2);

const result = await jsonCache.get('obj1');
console.log(result) // => {name: 'tes1', age: 21}


///// Using .rewrite()
const obj1 = {name: 'test1'}
await jsonCache.set('obj1', obj1);

const obj2 = {age: 21}
await jsonCache.rewrite('obj1', obj2);

const result = await jsonCache.get('obj1');
console.log(result) // => {age: 21}
```
Hope I've answered your question, if so please close this issue yourself, else leave a comment 🙂

**Comment by C0D1NGD0J0** [comment]
Thanks for the response, this helps :)
