### ISSUE TITLE
Multi / Exec capability

### ISSUE THREAD

**Issue by 920547** [AkashBabu/redis-json#13]
Hi: first of all, I think this is a great library!!!

The scenario that I'm facing is that right after storing an object into Redis, I need to add the key into a set as well, and both commands should happen within the same transaction (Multi / Exec). I manually execute the MULTI command from ioredis before calling the redis-json commands, and I'd like to have the option for redis-json to not execute the EXEC command internally, so I can combine more commands into a single transaction.

Thanks,

Franco

**Comment by AkashBabu** [comment]
Hi @920547 , this sounds like a good to have feature in the library. I'll work on it on priority.

**Comment by 920547** [comment]
Excellent, thanks! Let me know if I can be of any help.

**Comment by AkashBabu** [comment]
Sure will let you know if I need any help

**Comment by AkashBabu** [comment]
Hi @920547 , support for transactions have been introduced in v4.2.0. Please update your library to redis-json@4.2.0

Sample usage:
```JS
const transaction = ioRedisClient.multi();
transaction
  .set('name', 'foo')
  .set('bar', 'baz')

jsonCache.setT(transaction, 'test', {name: 'testing'})

transaction
  .exec((err, replies) => {
    /// your custom logic here. At this time all your transactions along with jsonCache would have been completed
  })
```
I'm sorry that I couldn't find a better solution expect for introducing new methods (setT, delT & rewriteT) because of the nature of redis transactions & redis-json library itself.

**Comment by 920547** [comment]
This  looks great to me! Thanks a lot!!!
