### ISSUE TITLE
Availability in Java?

### ISSUE THREAD

**Issue by razaellahi** [AkashBabu/redis-json#16]
Is this library is available in JAVA? so that both NODE and JAVA developers can use the same library.

**Comment by AkashBabu** [comment]
Hi @razaellahi , you can explore other libraries for Java which support storing JSON objects in Redis like https://github.com/RedisJSON/JRedisJSON but the scope of this library might not be to serve JAVA developers.
But if you want to work on a JAVA library for RedisJSON you can contact me anytime for any help regarding the same.

**Comment by razaellahi** [comment]
Yes
