### ISSUE TITLE
Support for numerical increments

### ISSUE THREAD

**Issue by Wazbat** [AkashBabu/redis-json#17]
Hi there,

This is initially a question. Is there any way to increment an integer without fetching the current value and saving the incremented value?

Based on my limited understanding of REDIS, isn't this supported natively by redis with INCR and HINCRBY?

**Comment by AkashBabu** [comment]
Great catch! I will take this up and will try to add this feature by EoD.

**Comment by AkashBabu** [comment]
Hey, please expect some delay, this feature will be completed by Wednesday EoD.

**Comment by Wazbat** [comment]
Awesome! I was half tempted to open a PR for this myself, but my knowledge is limited

I'd love it if this was similar to the way mongoDB does $inc calls. Like if I could do 
`cache.inc({messages: 1})` would increment the messages field by 1, -1 would reduce it by 1, 5 would increase by 5, etc. I'm unsure if 0 should throw an error, do nothing, or if to perform an inc call with 0. Though I'll leave all that up to you ^^

Thank you so much for this!

**Comment by AkashBabu** [comment]
Hey I was planning something very similar. Since we already support objects and nesting, we could use the same during other operation too. For Ex:
```JS
cache.exec(key, {messages: 10, profile: {age: 1}}, 'hincrby')
```
By supporting the above command we would be prepared even for future commands(if any). Then users can build specific actions like `incr`:
```JS
JSONCache.prototype.incr = function (key, obj) { 
  this.exec(key, {messages: 10, profile: {age: 1}}, 'hincrby')
}
```

Let me know your thoughts about it

**Comment by AkashBabu** [comment]
Hi @Wazbat , `.incr()` & `.incrT()`(for transactions) methods have been added in version `v4.3.0`. Please update your library and enjoy the feature you requested for🎉

**Comment by Wazbat** [comment]
Awesome! Thank you so much for this! I can't wait to test it out and stuff ^^
