### ISSUE TITLE
Option to set no prefix

### ISSUE THREAD

**Issue by ananthk324** [AkashBabu/redis-json#20]
Hi, I would like to have no prefix to be added to my keys. Giving no prefix option or giving an empty string in prefix results in a prefix of "jc:". Can you give an option to support no prefix?

This:
const jsonCache = new JSONCache(redis);
or
const jsonCache = new JSONCache(redis, { prefix: "" });
adds a prefix of "jc"

**Comment by AkashBabu** [comment]
Hey @ananthk324 , Thanks for reporting this. This seems to be a bug in the code which is occurring due to:
```TS
this.options.prefix = options.prefix || 'jc:';
```
I'll fix this in a while and let you know

**Comment by AkashBabu** [comment]
@ananthk324 Please update your library to `redis-json@5.0.0`.

**Comment by ananthk324** [comment]
Thanks for the quick update. Will update the library.
