### ISSUE TITLE
Type of get with no field arguments

### ISSUE THREAD

**Issue by craigsketchley** [AkashBabu/redis-json#25]
Hi there, great library btw. Just a quick question about the `get` type signature. Should it have at least two definitions where, if no field arguments are provided, then the return type is no longer `Partial<T>` but just `T`?

```typescript
interface IJSONCache<T> {
  // ...
  get(key: string): Promise<T | undefined>;
  get(key: string, ...fields: string[]): Promise<Partial<T> | undefined>;
  // ...
}
```

**Comment by AkashBabu** [comment]
Hi @craigsketchley , that's a great suggestion. Will definitely adopt it.

**Comment by AkashBabu** [comment]
Hi @craigsketchley , added the suggested types in version `v6.0.1`. Please update your library to use the same.
Once again, thanks for bringing this up 🙂
