### ISSUE TITLE
Set primitive types (like string, number, Boolean...)

### ISSUE THREAD

**Issue by jdanieljo** [AkashBabu/redis-json#27]
Primitive types are not saved in redis via `redis-json` lib.

```
const jsonCache = new JSONCache<string>(redisClient);
return jsonCache.set("key", "value");
```

**Comment by AkashBabu** [comment]
Hi @jdanieljo, for saving primitives in redis, you could simply use `redisClient.set(key, value)`. redis-json aims at saving only JSON data.
However, the only downside in saving primitives using `redisClient.set` is that the `type` would not be retained, which you will have to handle it yourself.
Please let me know if you need any help saving primitives.
