### ISSUE TITLE
Empty array is returned as string '[ ]'

### ISSUE THREAD

**Issue by chimek0** [AkashBabu/redis-json#28]
So sometimes when I store an empty array it's being returned as string '[ ]'. It doesnt happen very often but it occures.

simple case
```
await RedisJson.set('123', [])
const x = await RedisJson.get('123')
```

then sometimes x equals '[ ]'

version 
"redis-json": "^6.0.1",

**Comment by AkashBabu** [comment]
Hi @chimek0, Thanks for reporting this :) 
I just found that the test case for empty array has been missing. Will fix this by EoD

**Comment by AkashBabu** [comment]
@chimek0 , I just added the test case for empty array (related commit [here](https://github.com/AkashBabu/redis-json/commit/438676acac6909091d4788e6be0c4f305bfc1b54)) but did not find any issues with it. 
Please help me reproduce the issue, so that I can fix it.

**Comment by chimek0** [comment]
@AkashBabu thanks for response. As I said before it is not happening very often but it clearly does sometimes. We got a few production errors in our application due to this specific case. Currently we're doing some workaround checking if result is string or not, but we'd like to know how to avoid that.

**Comment by AkashBabu** [comment]
Hi @chimek0 , I'll see if I can find any edge cases in the code

**Comment by chimek0** [comment]
Hi @AkashBabu, thanks a lot :)
Please let me know if You find anything

**Comment by AkashBabu** [comment]
Hi @chimek0 , I tried debugging each and every step, but couldn't find any issues in the code. I also wrote a comprehensive list of tests to reproduce the same, but still failed.

Below are the list of tests which i tried. Incase you feel some edge case is missing, please let me know.
<img width="695" alt="Screenshot 2021-10-04 at 4 51 10 PM" src="https://user-images.githubusercontent.com/15184220/135842980-d597f916-1d22-4d88-9bb8-227344a2a903.png">

To better debug this issue, it would be great if you can share sequence of operations that you would perform on the cached data, so that I would be able to reproduce the issue.

**Comment by rafauq** [comment]
@AkashBabu thank you for fast response 

I think I found the issue. I could only reproduce this bug using http requests - sometimes I had to run multiple instances of the server on my localhost. this is the place in the code where bug happens:
file jsonCache.ts line 120
`    const [data, typeInfo] = await Promise.all([
      this.redisClientInt.hgetall(this.getKey(key)),
      this.redisClientInt.hgetall(this.getTypeKey(key)),
    ]);` 
    
After dubbuging this part of code I noticed that sometimes I get normal data object but typeInfo is empty. This leads to the situation where information about type is lost. Why does it happens?  First of all the sentence **"Node.js is single threaded"** is false, what is true is that NodeJS event loop is single threaded. I'll simplify things to one example: 
let's say we have 2 request to nodejs server sent at the same moment - if the server has enough resources they're not waiting for each-other to be completed, they will be processed in parallel. So when one of those requests asks for data for key 'a' and the other one is clearing data for key 'a' there may be situation where this line `this.redisClientInt.hgetall(this.getKey(key)),` 
will return data then cache is cleared and then line `this.redisClientInt.hgetall(this.getTypeKey(key)),` will return empty object.
So even if there is only one nodejs server this situation may happen - but we have multiple instances of nodejs servers so it happens quite often. Can you check if I'm right?

**Comment by AkashBabu** [comment]
@rafauq Thanks for the detailed explanation. This helps me to get started!

**Comment by AkashBabu** [comment]
@rafauq  @chimek0 I've fixed this issue in redis-json@6.0.2 Please update your library and check if this issue is still occurring.

**Comment by rafauq** [comment]
@AkashBabu Huge thanks from me and my team for fixing it so fast. I checked it locally for now because it will take some time to deploy your changes to the prod but the bug didn't happen so seems like your fix works fine. Once again thank you.

**Comment by AkashBabu** [comment]
Thank you for finding out the missing edge case :)
