### ISSUE TITLE
jsonCache.set with "expiry"

### ISSUE THREAD

**Issue by connectprabhjeet** [AkashBabu/redis-json#31]
Let a condition where we want to store the user's session, and the session is valid for only 1 day.
For now, there is no way to _expire_ it from Redis.

**Comment by AkashBabu** [comment]
I'm sorry that I missed to add it to the doc, however there is an option to expire while setting the token.
```TS
await jsonCache.set('123', user, {expire: 24 * 60 * 60 })
```
