### ISSUE TITLE
How to get the whole data from the cache?

### ISSUE THREAD

**Issue by samloba** [AkashBabu/redis-json#35]
Hi,
thx for the job.
is there a way to get the entire data from the cache? ex: jsonCache.getAll?

**Comment by AkashBabu** [comment]
Hi @samloba, currently there is no way to get the entire data from cache and we don't intend to provide support for it in the near future because the cached data can be huge and can possibly cause memory outage if we load everything. Hence I would suggest you to look for alternatives instead.

May I know your usecase ?

**Comment by samloba** [comment]
hi @AkashBabu 
thx for for your quick reply.

my use case:

My project is an Electron desktop application (windows 10/11) which embeds an express.js server and an sqlite database to serve a local web application for the management of a school.
One of the functionalities of the application is the control of the payment of school fees via a mobile application which scans a qrCode and sends it to the server which in turn makes an sql request and returns the result to the mobile application to display student status. This operation takes about 3s to execute because the sql query is a bit complex.
To solve this latency (and for other needs including session management), I added redis:
server: https://github.com/zkteco-home/redis-windows
client: https://github.com/luin/ioredis
cache: https://github.com/AkashBabu/redis-json (your module)
When initializing the school fee control functionality, I do the sql query globally (~10-25 s for 5000 students) and in a loop, I cache them in "schoolFees:studentID" format. 

> `//jsonCache.ts

> import redisJSON from "redis-json";

> import { redisClient } from ".";
> export const schoolFeesCache = new redisJSON<IschoolFees>(redisClient, {
>     prefix: 'schoolFees:',
>     stringifier: {
>         Date: (val) => val.toISOString()
>     },
>     parser: {
>         Date: (str) => new Date(str)
>     }
> });`

During execution the result is instantaneous (12ms) because the server retrieves the data directly from the cache!

So I would like to be able to retrieve all the data from the cache to display it on the web application and that's where I need the 'getAll' function (even if it should take me ~3-5 s)
I m exploring the possibility to use the logic of clearAll methode to iterate on keys and call get and push the result in an array that i will return.
Thx again for helping me

**Comment by AkashBabu** [comment]
> I m exploring the possibility to use the logic of clearAll methode to iterate on keys and call get and push the result in an array that i will return.

Well, even I would suggest doing the same as this will never overload your server and will still remain fast.

So, a rough code with pagination would look like:
```TS
async function getCacheKeys(offset = 0, limit = 10) {
  let cursor = '0';
  let result: string[];

  const totalScanLen = offset + limit;
  const scanCount = Math.min(totalScanLen, 50 /* change this as per your needs */)

  do {
    let keys: string[] = []
    [cursor, keys] = await this.redisClientInt.scan(
      cursor, 'MATCH', `schoolFees:*`, 'COUNT', scanCount,
    );

    result.push(...keys)
  } while (cursor !== '0' && result.length < totalScanLen);

  return result.slice(offset, totalScanLen);
}

async function getStudentStatuses(offset = 0, limit = 10) {
  const keys = await getCacheKeys(offset, limit);
  const list = await Promise.all(keys.map(key => jsonCache.get(key))
  return list;
}
```

**Comment by samloba** [comment]
waou! super rapid!!!
Let me try the code  and let you know
I will fork your project, add the getCacheKeys function in JSONCache.ts and call it with getStudentStatuses in my project. Right?
other thing:   to make getCacheKeys  reusable i will need to replace `schoolFees:*` and ignore the type keys ( *_t )
. Right?
thx

**Comment by AkashBabu** [comment]
> I will fork your project, add the getCacheKeys function in JSONCache.ts and call it with getStudentStatuses in my project. Right?

If you are planning to raise a PR, then I would suggest to use the following code:
```TS
async function getCacheKeys(offset = 0, limit = 10) {
  let cursor = '0';
  let result: string[];

  const totalScanLen = offset + limit;
  const scanCount = Math.min(totalScanLen * 2 /* every cache key has a type(_t) associated with it */, Config.SCAN_COUNT)

  do {
    let keys: string[] = []
    [cursor, keys] = await this.redisClientInt.scan(
      cursor, 'MATCH', `${this.options.prefix}*`, 'COUNT', scanCount,
    );

    result.push(...keys.filter(key => !key.endsWith('_t'))
  } while (cursor !== '0' && result.length < totalScanLen);

  return result.slice(offset, totalScanLen);
}
```


> other thing: to make getCacheKeys reusable i will need to replace schoolFees:* and ignore the type keys ( *_t )
. Right?

Yup, that's correct (please check the above code)

**Comment by samloba** [comment]
> If you are planning to raise a PR, then I would suggest to use the following code:

I'm not a seasoned developer but just an enthusiast. I will learn how to raise PR
Will you make a release including this?

**Comment by AkashBabu** [comment]
Cool! No worries, I misunderstood from your comments. 

> Will you make a release including this?

I don't have time right now, so sometime later maybe.

**Comment by samloba** [comment]
Very nice of you.
Thank you for your precious time that you gave me.
I will tinker something with the functions you gave me while waiting for the next version
A thousand times thank you

**Comment by AkashBabu** [comment]
You're welcome
