### ISSUE TITLE
Empty array is stored as empty string 

### ISSUE THREAD

**Issue by asennoussi** [AkashBabu/redis-json#4]
```
a = { category: '', title: '', description: [], authToken: '' }
jsonCache.set(userId, userQuestion, options)
```
On redis CLI 
```
HGETALL "Key:XXXXXXXXX"
1) "category"
2) "1"
3) "title"
4) ""
5) "description"
6) ""
7) "authToken"
8) ""
```

How can I make sure, description is stored as an empty array?

**Comment by AkashBabu** [comment]
@Sshuichi Currently there is no way you can do this. But this will be taken up as a feature request and you can expect it to be solved by the weekend.

**Comment by AkashBabu** [comment]
@Sshuichi As I was very much occupied over the weekend, I could not work on the issue. Since I'm currently moving the library to typescript, I will be releasing the fix along with typescript max by wednesday (18 Dec 2019). 

Hope you understand 🙂

**Comment by AkashBabu** [comment]
Please upgrade your library to `redis-json@3.0.0`.
