### ISSUE TITLE
Key with dots (.) splited into multiple key.

### ISSUE THREAD

**Issue by akif-ih** [AkashBabu/redis-json#6]
I am storing some keys into redis the keys contains . in them like "a.b.c" but redis-json split them into multiple keys.

**Comment by AkashBabu** [comment]
There is currently NO way to distinguish a `.` (DOT) in the key and hence we are treating it as a part of the flattened path.  
  So a temporary work around would be is to convert `.` to `-` or other character before saving it into RedisJson and revert it back on `get`.  
  Permanent Solution from my end would be to encode the `.` character and decode it when retrieving back from redis, which my take some time over this weekend. So if you can wait till the weekend, then just sit back and relax for the next release, else if you are in a hurry, then use the temporary solution.

**Comment by AkashBabu** [comment]
Hi @akif-ih please upgrade your library to v3.2.0 as this issue has been addressed in the latest version.
